language: cpp
dist: xenial

# More builds expected in the future
matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - deadsnakes
          packages:
            - g++-9
            - python3.5
      env:
        - MATRIX_EVAL="CXX_COMPILER=g++-9"
    
before_install:
  - eval "${MATRIX_EVAL}"

  - PARENTDIR=$(pwd)
  
  - mkdir $PARENTDIR/build
  - mkdir $PARENTDIR/build-release
  - mkdir $PARENTDIR/build-asan

  - bash scripts/install_cpputest.sh

install:

script:
  - export CC=gcc-9
  - export CXX=g++-9

  - cd $PARENTDIR/build
  - cmake $PARENTDIR/src -DCMAKE_BUILD_TYPE=Debug
  - make -j9

  - cd $PARENTDIR/build-release
  - cmake $PARENTDIR/src -DCMAKE_BUILD_TYPE=Release
  - make -j9

  - cd $PARENTDIR/build-asan
  - cmake $PARENTDIR/src -DCMAKE_BUILD_TYPE=Release -DWITH_ASAN=ON
  - make -j9

  - cd $PARENTDIR/checks
  - python3 semantic_failures/run.py $PARENTDIR/build/titan
