/* This header is autogenerated by CMAKE  */

#ifndef VTITAN_SETTINGS_HPP
#define VTITAN_SETTINGS_HPP

namespace VTITAN {
class Settings {

public:
  static constexpr char VERSION_MAJOR[] = "0";
  static constexpr char VERSION_MINOR[] = "1";
  static constexpr char VERION_PATCH[] = "0";
  static constexpr char BUILD_PLATFORM[] = "APPLE";

  void set_something();

private:
};
} // namespace VTITAN

#endif
